[WIP] Add action to delete iam server cert
cloud-custodian/cloud-custodian pull request #6288
Opened 2020-11-12 14:55 UTC by dnouri

Consider the `action` in this example:

```yaml
        - name: aws-iam-certificate-delete-expired
          resource: iam-certificate
          filters:
            - type: value
              key: Expiration
              value_type: expiration
              op: greater-than
              value: 0
          actions:
            - type: delete
```

2020-11-12 16:08 UTC, kapilt commented on c7n/resources/iam.py
> +                ServerCertificateName=cert['ServerCertificateName'],
pass ignore_err_code to not raise for certificates already deleted/in progress on deletion.

2020-11-12 16:09 UTC, kapilt commented on c7n/resources/iam.py
> +#     "Path": "/",
this looks like noise, please remove.

2020-11-12 16:10 UTC, kapilt commented on tests/test_iam.py
> +        client.get_server_certificate(ServerCertificateName=iam_name)
remove this api call, and add the assertion on server cert name to the policy as an attribute filter

2020-11-12 16:11 UTC, kapilt requested changes
comments inline

2020-12-01 13:59 UTC, kapilt approved these changes
lgtm

2020-12-01 14:00 UTC, marcoceppi approved these changes
lgtm

2020-12-01 14:05 UTC, merged