Clarify execution mode wording and add cross references.
cloud-custodian/cloud-custodian pull request #6861
Opened 2021-08-20 18:19 UTC by castrojo

Please take a look @liz-acosta

2021-08-23 23:46 UTC, liz-acosta commented on docs/source/aws/lambda.rst
> +Lambdas can receive CWE over CloudTrail API calls with seconds of delay at P99.
I would call out what "CWE" stands for when it first occurs, which is line 32. That line would become

```
Custodian provides for policy level execution against any CloudWatch Events stream. Henceforth "CloudWatch Events" will be abbreviated as CWE.
```

2021-08-23 23:55 UTC, liz-acosta requested changes
Left comments for further documentation clarity

2021-08-23 23:55 UTC, liz-acosta commented on docs/source/aws/lambda.rst
> +Lambdas can receive CWE over CloudTrail API calls with seconds of delay at P99.
`with seconds of delay at P99` --> `within seconds of delay at P99`

2021-08-23 23:55 UTC, liz-acosta commented on docs/source/aws/lambda.rst
> +list of configuration options for this execution mode:
`for a list of configuration options for this execution mode:` --> `for a list of other configurable options`

2021-08-23 23:55 UTC, liz-acosta commented on docs/source/aws/lambda.rst
> +Refer to `AWS execution modes documentation
Same as line 84 above

2021-08-30 16:45 UTC, kapilt commented on docs/source/aws/lambda.rst
> +stream. Henceforth "CloudWatch Events" will be abbreviated as CWE. Each
s/stream/source

2021-08-30 16:48 UTC, kapilt commented on docs/source/aws/lambda.rst
> +stream. Henceforth "CloudWatch Events" will be abbreviated as CWE. Each
hmm actually thats the term they use upstream.. so lgtm

2021-08-30 16:49 UTC, kapilt approved these changes
lgtm

2021-08-30 16:49 UTC, merged