aws - efs - add has-statement filter
cloud-custodian/cloud-custodian pull request #7884
Opened 2022-10-14 21:24 UTC by StevenGunn

This adds support to filter on AWS EFS file system policies:

```
    filters:
      - not:
        - type: has-statement
          statements:
            - Effect: "Allow"
              Condition:
                Bool:
                  "elasticfilesystem:AccessedViaMountTarget": "true"
              Resource: "{fs_arn}"
```

2022-10-21 07:25 UTC, StevenGunn commented
@thisisshi can you check this one out when you get a chance?

2022-11-08 19:47 UTC, thisisshi requested changes

2022-11-08 19:47 UTC, thisisshi commented on c7n/resources/efs.py
> +import c7n.filters.policystatement as polstmt_filter
```suggestion
from c7n.filters.policystatement import HasStatementFilter
```

2022-11-08 19:47 UTC, thisisshi commented on c7n/resources/efs.py
> +class HasStatementFilter(polstmt_filter.HasStatementFilter):
```suggestion
class EFSHasStatementFilter(HasStatementFilter):
```

2022-11-15 20:49 UTC, StevenGunn commented
@thisisshi requested changes have ben made, can you please review/approve when you can?

2022-11-15 20:51 UTC, thisisshi approved these changes

2022-11-22 20:00 UTC, merged