aws - lambda - added assume role for invoke lambda
cloud-custodian/cloud-custodian pull request #7904
Opened 2022-10-18 19:52 UTC by sgungi-intuit

Added logic to create client to assume role arn and invoke lambda. 

@darrendao @kapilt @ajkerrigan @thisisshi

2022-10-19 19:06 UTC, thisisshi commented on tests/test_s3.py
> +                "arn:aws:iam::213925950568:role/service-role/lanbda-invoke-c7n-role-py5l2hbi"}],
please remove your account id here

2022-10-19 19:09 UTC, thisisshi commented
Thanks for the contirbution, there's a lot of extraneous test data in here, s3 is not a great resource to use for tests unless you modify the augment table to make fewer API calls. Please modify the test so that it doesnt record as much extra data. Additionally it doesn't look like there's an actually lambda invoke call in the test data, is it actually making the call and can you assert that the role was passed through? Thanks

2022-10-19 19:10 UTC, thisisshi commented on tests/test_s3.py
> +        session_factory = self.replay_flight_data("test_s3_invoke_lambda_assume_role")
please patch the executor factory and augment table if you're going to use the s3 resource for testing. This reduces the amount of extra test data we record

```python
self.patch(s3.S3, "executor_factory", MainThreadExecutor)
self.patch(s3, "S3_AUGMENT_TABLE", [])
```

2022-10-20 14:23 UTC, kapilt approved these changes
lgtm

2022-10-20 14:45 UTC, kapilt commented
the testing around this will need to be adjusted as recording a temporary credential will always fail over time. we probably need to mock the assumed_session in this context.

2022-10-20 15:34 UTC, sgungi-intuit commented
Thanks @kapilt, will update the test case to mock assume creds.

2022-11-07 15:37 UTC, sgungi-intuit commented
Hi @kapilt, the test code is updated to mock assumed_session.

2022-11-09 18:33 UTC, thisisshi commented on tests/test_s3.py
> +    def test_s3_invoke_lambda_assume_role_action(self, mock_assumed_session):
there aren't any actual assertions in this test, we need to assert that the assumed session is actually being used

2022-11-09 18:33 UTC, thisisshi requested changes
there aren't any actual assertions in this test, we need to assert that the assumed session is actually being used

2022-11-17 21:30 UTC, merged