add some docs for c7n-kube
cloud-custodian/cloud-custodian pull request #7922
Opened 2022-10-21 21:05 UTC by djeebus

I also added `--host` to the list of options taken by c7n-kube, which defaults to listening to localhost, for standard practice security purposes.

2022-10-21 21:17 UTC, thisisshi requested changes

2022-10-21 21:17 UTC, thisisshi commented on tools/c7n_kube/readme.md
> +c7n-kube can be run and installed via poetry. `poetry install && poetry run c7n-kates`.
```suggestion
c7n-kates can be run and installed via poetry. `poetry install && poetry run c7n-kates`.  
```

2022-10-21 21:17 UTC, thisisshi commented on tools/c7n_kube/readme.md
> +Cloud custodian can run policies directly inside your cluster, reporting on
```suggestion
Cloud Custodian can run policies directly inside your cluster, reporting on 
```

2022-10-21 21:29 UTC, djeebus commented
@thisisshi oops, thanks for the :eye: !

2022-10-22 14:08 UTC, kapilt reviewed
lgtm overall, but needs fixing re failing tests.

2022-10-24 09:17 UTC, kapilt approved these changes
lgtm

2022-10-24 09:18 UTC, merged