Activity log alerts resource creation
cloud-custodian/cloud-custodian pull request #8167
Opened 2023-01-17 16:15 UTC by vkagusa-mckinsey

creating a custodian resource of Activity alert logs.

2023-01-17 16:57 UTC, thisisshi commented
please add a test for this

2023-01-17 18:09 UTC, vkagusa-mckinsey commented
> please add a test for this

test is added.

2023-01-17 19:01 UTC, thisisshi requested changes
looks like it's missing the actual python test file

2023-01-20 19:59 UTC, vkagusa-mckinsey commented on tools/c7n_azure/c7n_azure/resources/alertlogs.py
> +@resources.register('alert_logs')
Done.

2023-01-20 19:59 UTC, vkagusa-mckinsey commented on tools/c7n_azure/c7n_azure/resources/alertlogs.py
> +@resources.register('alert_logs')
Done.

2023-01-20 19:59 UTC, vkagusa-mckinsey commented on tools/c7n_azure/c7n_azure/resources/alertlogs.py
> +@resources.register('alert_logs')
Done.

2023-01-23 14:51 UTC, dslagle commented
@thisisshi I think everything has been corrected. Can you confirm?

2023-01-23 19:54 UTC, thisisshi approved these changes
thanks, lgtm

2023-01-23 20:55 UTC, merged