aws - bedrock custom models
cloud-custodian/cloud-custodian pull request #9161
Opened 2023-11-20 21:07 UTC by PratMis

Closes #9133

2023-11-20 21:15 UTC, PratMis commented
Looks like there's one test in the CC provider that's failing

2023-11-20 22:16 UTC, ajkerrigan commented
Be resilient to upstream API additions
```diff
diff --git a/tools/c7n_awscc/tests/test_ccmanager.py b/tools/c7n_awscc/tests/test_ccmanager.py
index 2b00bd9df5..531443980b 100644
--- a/tools/c7n_awscc/tests/test_ccmanager.py
+++ b/tools/c7n_awscc/tests/test_ccmanager.py
@@ -13,7 +13,7 @@ def test_init_resource_access_analyzer():
 def test_update_schema():
     klass = initialize_resource("eks_cluster")["EksCluster"]
     update_schema = get_update_schema(klass.schema, "eks_cluster")
-    assert set(update_schema["properties"]) == {
+    assert set(update_schema["properties"]) >= {
         "Tags",
         "Version",
         "ResourcesVpcConfig",

```

2023-11-21 14:14 UTC, ajkerrigan commented
> I think this is related to #9158 & #9146, and I wonder if instead of (or in addition to) a meta test with some shape inspection, we could make the test more resilient to upstream API additions without sacrificing its value. Like:

#9165 should take care of the failing awscc test.

2023-11-21 16:35 UTC, ajkerrigan requested changes
Functionality looks good to me, couple minor suggestions inline. Thanks for working on this :+1:

2023-11-21 19:13 UTC, PratMis commented on c7n/resources/bedrock.py
> +@resources.register('bedrock-custom-models')
Yup, this makes sense. Fixed it, thanks for flagging

2023-11-21 19:14 UTC, PratMis commented on c7n/resources/bedrock.py
> +        arn = "modelArn"
Addressed

2023-11-21 19:15 UTC, ajkerrigan approved these changes
Looks good to me, thanks again! :+1:

2023-11-21 19:29 UTC, merged