aws - cost optimization filter
cloud-custodian/cloud-custodian pull request #9209
Opened 2023-12-19 13:14 UTC by kapilt

initial focus on resource level optimizations, versus ri/savings plan on account.

2023-12-20 14:58 UTC, ajkerrigan requested changes
LGTM aside from one point inline about handling filter-defined action types. This looks handy to support, thanks! :+1:

2023-12-21 14:40 UTC, kapilt commented on c7n/filters/costhub.py
> +                self.manager.data.get('action') and [self.manager.data.get('action')]
to simplify remediation policies, I'm going to force this to a scalar

2023-12-21 14:40 UTC, kapilt commented on c7n/filters/costhub.py
> +        action={
with a move to a scalar action extant name should be okay.

2023-12-21 14:54 UTC, ajkerrigan approved these changes
Cool cool, looks good to me :+1:

2023-12-21 15:07 UTC, merged