azure - filter - use retry
cloud-custodian/cloud-custodian pull request #9363
Opened 2024-03-19 04:19 UTC by iamanmolm

This fixes issue reported in https://github.com/cloud-custodian/cloud-custodian/issues/9346

2024-03-20 11:03 UTC, kapilt commented on c7n/utils.py
> +from azure.core.exceptions import HttpResponseError
this should go into c7n_azure utils, rather then creating a hard dependency on azure for the base package. Also note there is separate retry handling there custodian_send_azure_override as an example that tries to incorporate this into the base client.

2024-03-20 11:04 UTC, kapilt requested changes
azure specific retry logic should be in the c7n_azure package.

2024-07-22 20:06 UTC, kapilt commented
Closing due to lack of response or addressing pr feedback.

2024-07-22 20:06 UTC, closed without merging

2024-08-22 06:40 UTC, iamanmolm commented
> This fixes issue reported in #9346

Hey @kapilt, sorry I got occupied with other high priority items and could not respond on this one.
I have now assigned time to work on this issue and have created a new PR with the suggested changes: https://github.com/cloud-custodian/cloud-custodian/pull/9682

Sorry for the inconvenience caused, looking forward to your reviews on the new PR.

Thanks in advance!!